### ISSUE TITLE
test/client/fetch-reports:  data format

### ISSUE THREAD

**Issue by Benjamin0203** [jakinyang/minaa#42]
Trying to replace mock  report data with database and change the mock data format to data base

**Comment by jakinyang** [comment]
Great catch on this issue:
1. I think the approach of changing the format of the mock data to match the real data returned by the server is good:
2. Test that the new correct formatted mock data works well, and make any changes as necessary.
3. Finally, once everything works with the new mock data, implement it with the real data fetched from the database.

**Comment by jakinyang** [comment]
Does the datafetching for the report data actually work? When you console log the reports data that you fetched, does it log correctly?

**Comment by jakinyang** [comment]
> Great catch on this issue:
> 
> 1. I think the approach of changing the format of the mock data to match the real data returned by the server is good:
> 2. Test that the new correct formatted mock data works well, and make any changes as necessary.
> 3. Finally, once everything works with the new mock data, implement it with the real data fetched from the database.

By this I mean that check that MapViewScreen, MapPins, and everything else can handle the data correctly

**Comment by Benjamin0203** [comment]
> Does the datafetching for the report data actually work? When you console log the reports data that you fetched, does it log correctly?

Yes, here's the query and result:
Query: `query Query {
      reports {
        id
        latitude
        longitude
        description
        radius
        statusCategory
        reportCategory
        imageUrl
        createdAt
        updatedAt
      }
    }`
Console.log(data.reports):
`[... ,{"__typename": "Report", "createdAt": "2023-01-09T21:44:08.961Z", "description": "Dolorum labore velit aspernatur.", "id": "18", "imageUrl": "https://loremflickr.com/640/480", "latitude": -70.111398, "longitude": -58.052633, "radius": 5, "reportCategory": "UNCLEAR", "statusCategory": "REPORTED", "updatedAt": "2023-01-09T21:44:08.961Z"}, ...]`
just not sure about the `_typename` and `Report` in each array item

**Comment by jakinyang** [comment]
I think there is a second issue here:

1. When we longPress on MapViewScreen and start the process of making a new pin, we make two data objects and hand them off to tempCoords and pinData.
2. We do this because we want the map to show the pin when a user long presses and then begin the process of making a new report by showing the modal and redirecting the the NewReportScreen.
3. The issue here is that when we set the tempCoords and the pinData inside of MapViewScreen, and then pass that on to other components, we are editing pinData which is supposed to ***only*** reflect the data that comes from the database. 

So we need to keep these things clean and separate somehow....

I think that one approach to this is to do the following: 

1. We make a second instance of the MapPins component, we'll nickname it "Temporary Local MapPins"
2. This will be inside of HomeScreen along side the other MapPins (we'll call this "Fetched MapPins") component that renders pins/reports with the data fetched from the database.
3. When the app loads
- the Apollo client will fetch the report data from the database
- "Fetched MapPins" will render this report data as pins on the map
- Next the user longPresses on the map to make a new report
- This event is handled by the "onLongPress" handler inside of Map component in MapViewScreen
- (Right now, our onLongPress handler takes the new event data (i.e. e.nativeEvent.coordinate.latitude) and then adds this data into tempCoords ***AND*** pinData => We're doing this because this is the only way we have right now to render the pin on the map as soon as the user long-presses)
- What we could do **instead** is to NOT put this data into pinData.
- Instead, we create another "useFreshState" variable inside of HomeScreen (let's give a nickname "temporaryPinData and setTemporaryPinData")
- So now onLongPress takes the data (i.e. e.nativeEvent.coordinate.latitude, etc.) puts that into the "tempReport" variable (i.e. const tempReport = { id: null, ... }) and uses setTemporaryPinData to put this information into temporaryPinData.

Now what?

In Homescreen, we established that we have two MapPins components "Fetched MapPins" (which renders data from the database) and "Temporary Local MapPins"
- "Temporary Local MapPins" will use only the data stored in "temporaryPinData" to render pins
- this will go through the normal process of going to the NewReportscreen and saving it
- then when this new report data is sent to the back end, 
- we wait for the response to come back positive, and then we take the new updated report data from the database, and then we render the latest, new report on the screen.
- But now we have a problem - we still have the pin from TemporaryLocal MapPins AND we have the SAME pin stored, retrieved, and rendered by Fetched MapPins
- the solution is then to delete all the data inside of temporaryPinData, which will remove all the pins rendered by Temporary Local MapPins

**Comment by Benjamin0203** [comment]
This solution is so well considered. So from my understanding the process will be:
- fetch data  as `fetchedReportData`--> store inside component `TemporaryLocalPins` --> renders the pins with the real database reports; 
- onLongPress --> adds lat and lon into `tempCoords` and `pinData`
- create `const [temporaryPinData, setTemporaryPinData] = useFreshState({latitude: 0, longitude: 0}) ` and then insert the lat and lon inside  `temporaryPinData`
- open a new report screen, submit --> send to database --> take the newest reports data from database, renders on the map 
- delete tempPinData and we have only updated pins

Please let me know if I am understanding correctly. Thank you!

**Comment by jakinyang** [comment]
> Yes, here's the query and result: Query: `query Query { reports { id latitude longitude description radius statusCategory reportCategory imageUrl createdAt updatedAt } }` Console.log(data.reports): `[... ,{"__typename": "Report", "createdAt": "2023-01-09T21:44:08.961Z", "description": "Dolorum labore velit aspernatur.", "id": "18", "imageUrl": "https://loremflickr.com/640/480", "latitude": -70.111398, "longitude": -58.052633, "radius": 5, "reportCategory": "UNCLEAR", "statusCategory": "REPORTED", "updatedAt": "2023-01-09T21:44:08.961Z"}, ...]` just not sure about the `_typename` and `Report` in each array item

Nice that's good.

**Comment by jakinyang** [comment]
> This solution is so well considered. So from my understanding the process will be:
> 
> * fetch data  as `fetchedReportData`--> store inside component `TemporaryLocalPins` --> renders the pins with the real database reports;

No: the process is 'fetchedReportData' ==> store in state 'pinData' ==> render in component 'fetchedMapPins'

> * onLongPress --> adds lat and lon into `tempCoords` and `pinData`

No: onLongPress ==> adds lat/long to 'tempCoords', adds temporary data to const tempReport ==> stores in "temporaryPinData" ==> renders with "Temporary Local MapPins"

> * create `const [temporaryPinData, setTemporaryPinData] = useFreshState({latitude: 0, longitude: 0}) ` and then insert the lat and lon inside  `temporaryPinData`
> * open a new report screen, submit --> send to database --> take the newest reports data from database, renders on the map
> * delete tempPinData and we have only updated pins
> 
> Please let me know if I am understanding correctly. Thank you!

**Comment by jakinyang** [comment]
> This solution is so well considered. So from my understanding the process will be:
> 
> * fetch data  as `fetchedReportData`--> store inside component `TemporaryLocalPins` --> renders the pins with the real database reports;

No: the process will be:
FETCH DATA FROM DATABASE ==> store in "pinData" ==> rendered by "Fetched MapPins"

> * onLongPress --> adds lat and lon into `tempCoords` and `pinData`

No: 
onLongPress ==> event data (e....longitude, etc) stored in tempCoords ==> AND THNE tempReport ==> stored in "temporaryPinData"

> * create `const [temporaryPinData, setTemporaryPinData] = useFreshState({latitude: 0, longitude: 0}) ` and then insert the lat and lon inside  `temporaryPinData`

No:

const [temporaryPinData, setTemporaryPinData] = useFreshState(null) at first, and it should be made ahead of time before the long press event. the tempReport variable made in the onLongPress handler in MapViewScreens should be stored inside of this state (temporaryPinData)

THEN: this data (temporaryPinData) is given to ==> rendered by"Temporary Local MapPins" so that the users latest report is immediately rendered on the map

> * open a new report screen, submit --> send to database --> take the newest reports data from database, renders on the map

Yes: open a new report, but the data that we handed to temporaryPinData will be immediately given to Temporary Local MapPins to render AND we will hand this data over to the dialogue pop up ==> NewReportScreen so that they can manipulate it and add data to the new report ==> submit that new report data ==> send new report data to back end

Wait for response then...

> * delete tempPinData and we have only updated pins

Yes: when we get the response back from the backend that the new report successfully saved to the database, we can update pinData with the new report, we can delete the data from temproaryPinData, Temporary Local MapPins will no longer render any pins, and Fetched MapPins will render all the pins including the latest new report that was just made.

> Please let me know if I am understanding correctly. Thank you!

Good luck!

**Comment by Benjamin0203** [comment]
That was well explained! Thanks
